package com.example.mini_projet.spyfall.game;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Word bank organized by theme. Each theme has 500+ words.
 * Call WordList.getRandom(themes) with a set of selected theme names,
 * or getRandom() to pick from all themes.
 */
public final class WordList {

    private WordList() {}

    public enum Theme {
        OBJECTS   ("📦", "Everyday Objects"),
        PLACES    ("🗺️", "Places"),
        FOOD      ("🍕", "Food & Drinks"),
        TECH      ("💻", "Tech & Internet"),
        ANIMALS   ("🐾", "Animals"),
        JOBS      ("💼", "Jobs & Professions"),
        SPORTS    ("⚽", "Sports & Games"),
        SCHOOL    ("📚", "School & Study"),
        FUN       ("🎭", "Random & Fun");

        public final String emoji;
        public final String label;
        Theme(String emoji, String label) { this.emoji = emoji; this.label = label; }
    }

    // ── EVERYDAY OBJECTS (500+) ───────────────────────────────────────────────
    private static final String[] OBJECTS = {
            "Phone","Charger","Backpack","Notebook","Pen","Pencil","Eraser","Marker",
            "Headphones","Watch","Wallet","Keys","Mirror","Glasses","Bottle","Cup",
            "Plate","Spoon","Fork","Knife","Pillow","Blanket","Door","Window",
            "Chair","Table","Lamp","Remote","Television","Laptop","Keyboard","Mouse",
            "Speaker","Camera","Fan","Air Conditioner","Refrigerator","Microwave",
            "Oven","Stove","Soap","Towel","Toothbrush","Toothpaste","Shampoo",
            "Perfume","Shoes","Jacket","Hat","Sunglasses","Umbrella","Clock",
            "Battery","Flashlight","Candle","Scissors","Comb","Razor","Bag",
            "Suitcase","Helmet","Microphone","Controller","Gamepad","Printer",
            "Router","Cable","Power Bank","Thermos","Bucket","Broom","Mop",
            "Dustpan","Vacuum","Iron","Ironing Board","Clothes Hanger","Wardrobe",
            "Dresser","Shelf","Bookcase","Nightstand","Alarm Clock","Curtain",
            "Carpet","Rug","Doormat","Cushion","Sofa","Armchair","Rocking Chair",
            "Desk Lamp","Ceiling Fan","Light Switch","Power Strip","Extension Cord",
            "Stapler","Tape","Glue","Ruler","Compass","Protractor","Whiteboard Marker",
            "Sticky Note","Paper Clip","Binder","Folder","Filing Cabinet","Envelope",
            "Stamp","Letter","Parcel","Box","Crate","Bin","Trash Can","Recycling Bin",
            "Laundry Basket","Clothespin","Drying Rack","Washing Machine","Dryer",
            "Dishwasher","Kitchen Sink","Faucet","Sponge","Dish Rack","Colander",
            "Cutting Board","Rolling Pin","Mixing Bowl","Whisk","Spatula","Ladle",
            "Pot","Pan","Wok","Pressure Cooker","Rice Cooker","Blender","Juicer",
            "Toaster","Coffee Maker","Kettle","Tray","Lunch Box","Water Bottle",
            "Thermos Flask","Mug","Glass","Wine Glass","Chopsticks","Tongs",
            "Peeler","Grater","Can Opener","Bottle Opener","Corkscrew","Timer",
            "Measuring Cup","Measuring Spoon","Baking Tray","Muffin Tin","Oven Mitt",
            "Apron","Kitchen Towel","Napkin","Tablecloth","Placemat","Coaster",
            "Flower Vase","Picture Frame","Photo Album","Candle Holder","Incense",
            "Air Freshener","Mosquito Coil","Bug Spray","Sunscreen","Lotion",
            "Cotton Ball","Cotton Swab","Bandage","Thermometer","Medicine Box",
            "Pill Organizer","Inhaler","Nasal Spray","Eye Drops","Heating Pad",
            "Hot Water Bottle","Ice Pack","Tweezers","Nail Clipper","Nail File",
            "Hair Dryer","Hair Straightener","Curling Iron","Hair Brush","Hair Clip",
            "Bobby Pin","Hairband","Scrunchie","Makeup Brush","Foundation","Lipstick",
            "Mascara","Eyeliner","Concealer","Blush","Powder","Eyeshadow","Highlighter",
            "Nail Polish","Nail Polish Remover","Face Mask","Moisturizer","Toner",
            "Serum","Sunblock","Deodorant","Body Wash","Bath Bomb","Loofah",
            "Razor Blade","Shaving Cream","Aftershave","Cologne","Hair Gel",
            "Dry Shampoo","Conditioner","Hair Mask","Face Wash","Scrub",
            "Dental Floss","Mouthwash","Tongue Scraper","Electric Toothbrush",
            "Shaving Brush","Safety Pin","Sewing Kit","Thread","Needle","Thimble",
            "Tape Measure","Scissors","Seam Ripper","Knitting Needle","Crochet Hook",
            "Yarn","Fabric","Button","Zipper","Velcro","Elastic Band","Ribbon",
            "Wrapping Paper","Gift Bag","Bow","Tape Dispenser","Glue Gun","Glue Stick",
            "Sticker","Label Maker","Hole Punch","Shredder","Calculator","Abacus",
            "Globe","Map","Compass Rose","Magnifying Glass","Binoculars","Telescope",
            "Microscope","Test Tube","Beaker","Petri Dish","Pipette","Bunsen Burner",
            "Safety Goggles","Lab Coat","Rubber Gloves","Surgical Mask","Stethoscope",
            "Blood Pressure Cuff","Syringe","Scalpel","Forceps","Gauze","Splint",
            "Crutches","Walking Stick","Wheelchair","Hearing Aid","Glasses Case",
            "Contact Lenses","Contact Lens Case","Reading Glasses","Sunglasses Case",
            "Watch Band","Ring","Bracelet","Necklace","Earrings","Brooch","Anklet",
            "Tie","Bow Tie","Belt","Suspenders","Scarf","Gloves","Mittens","Beanie",
            "Beret","Cap","Fedora","Cowboy Hat","Hard Hat","Swim Cap","Shower Cap",
            "Raincoat","Windbreaker","Hoodie","Sweatshirt","Cardigan","Vest","Tank Top",
            "T-shirt","Polo Shirt","Dress Shirt","Blouse","Skirt","Dress","Jumpsuit",
            "Overalls","Jeans","Trousers","Shorts","Leggings","Tights","Socks",
            "Ankle Socks","Knee Socks","Stockings","Underwear","Sports Bra","Pajamas",
            "Bathrobe","Slippers","Flip Flops","Sandals","Sneakers","Boots","Heels",
            "Loafers","Oxford Shoes","Ballet Flats","Rain Boots","Hiking Boots",
            "Cleats","Roller Skates","Ice Skates","Ski Boots","Swim Fins","Snorkel",
            "Swimming Goggles","Life Jacket","Bicycle Helmet","Knee Pads","Elbow Pads",
            "Wrist Guard","Mouthguard","Boxing Gloves","Shin Guards","Shoulder Pads",
            "Baseball Glove","Football Helmet","Cricket Bat","Tennis Racket","Badminton Racket",
            "Ping Pong Paddle","Golf Club","Hockey Stick","Lacrosse Stick","Ski Poles",
            "Snowboard","Surfboard","Skateboard","Scooter","Bicycle","Tricycle",
            "Wheelchair","Stroller","Baby Carrier","Car Seat","High Chair","Crib",
            "Baby Monitor","Baby Bottle","Pacifier","Diaper","Wipes","Rattle",
            "Stuffed Animal","Action Figure","Doll","Building Blocks","Puzzle",
            "Board Game","Playing Cards","Dice","Chess Set","Checkers","Dominos",
            "Jenga","Yo-Yo","Kite","Frisbee","Jump Rope","Hula Hoop","Bubbles",
            "Sidewalk Chalk","Coloring Book","Crayon","Watercolor","Paint Brush",
            "Canvas","Sketchbook","Pencil Case","Art Easel","Clay","Playdough",
            "Lego","Remote Control Car","Train Set","Dollhouse","Action Set",
            "Water Gun","Nerf Gun","Foam Sword","Cape","Mask","Costume",
            "Musical Instrument","Guitar","Ukulele","Piano","Keyboard","Violin",
            "Cello","Flute","Clarinet","Saxophone","Trumpet","Trombone","Drums",
            "Tambourine","Maracas","Harmonica","Accordion","Banjo","Harp","Lyre",
            "Music Stand","Sheet Music","Metronome","Tuner","Capo","Bow","Rosin",
            "Mute","Strap","Pick","Drumstick","Pedal","Amplifier","Microphone Stand",
            "Mixing Board","Headset","Earbuds","Wireless Earbuds","Soundbar",
            "Subwoofer","Turntable","Record","Cassette Tape","CD","DVD","Blu-ray",
            "VHS Tape","VCR","Projector","Screen","HDMI Cable","USB Hub","Docking Station",
            "External Hard Drive","Flash Drive","Memory Card","SD Card","SIM Card",
            "Charger Cable","Wireless Charger","Battery Pack","Solar Panel","Generator",
            "Extension Lead","Surge Protector","Smart Plug","Smart Bulb","Dimmer Switch",
            "Thermostat","Smoke Detector","Carbon Monoxide Detector","Security Camera",
            "Doorbell","Intercom","Door Lock","Deadbolt","Padlock","Combination Lock",
            "Key Ring","Key Holder","Shoe Rack","Coat Hook","Umbrella Stand",
            "Magazine Rack","Newspaper","Magazine","Comic Book","Dictionary","Thesaurus",
            "Encyclopedia","Atlas","Almanac","Cookbook","Recipe Book","Journal",
            "Diary","Planner","Calendar","To-Do List","Whiteboard","Chalkboard",
            "Bulletin Board","Pushpin","Whiteboard Eraser","Dry Erase Marker"
    };

    // ── PLACES (500+) ─────────────────────────────────────────────────────────
    private static final String[] PLACES = {
            "School","Mosque","Beach","Desert","Mountain","Stadium","Cafe","Restaurant",
            "Mall","Market","Airport","Hospital","Pharmacy","Gym","Cinema","Park",
            "Hotel","House","Apartment","Garage","Library","Museum","Zoo","Aquarium",
            "Amusement Park","Water Park","Bowling Alley","Ice Rink","Skating Rink",
            "Swimming Pool","Golf Course","Tennis Court","Basketball Court","Football Field",
            "Baseball Diamond","Running Track","Boxing Gym","Martial Arts Studio",
            "Dance Studio","Yoga Studio","Pilates Studio","Fitness Center","Spa",
            "Sauna","Hot Tub","Jacuzzi","Beauty Salon","Barbershop","Nail Salon",
            "Tattoo Parlor","Piercing Studio","Tanning Salon","Laundromat","Dry Cleaner",
            "Tailor Shop","Shoe Repair","Watch Repair","Jeweler","Pawn Shop",
            "Antique Shop","Thrift Store","Consignment Shop","Flea Market","Farmers Market",
            "Grocery Store","Supermarket","Convenience Store","Corner Store","Bakery",
            "Butcher Shop","Fish Market","Deli","Cheese Shop","Wine Shop","Liquor Store",
            "Coffee Shop","Tea House","Juice Bar","Ice Cream Parlor","Candy Store",
            "Chocolate Shop","Pastry Shop","Donut Shop","Pizza Place","Burger Joint",
            "Taco Stand","Food Truck","Food Court","Buffet","Cafeteria","Diner",
            "Bistro","Brasserie","Steakhouse","Seafood Restaurant","Sushi Bar",
            "Ramen Shop","Noodle House","Dim Sum Restaurant","Pho Shop","Curry House",
            "Mexican Restaurant","Italian Restaurant","Greek Restaurant","Lebanese Restaurant",
            "Indian Restaurant","Thai Restaurant","Vietnamese Restaurant","Korean BBQ",
            "Japanese Restaurant","Chinese Restaurant","Turkish Restaurant","Moroccan Restaurant",
            "Ethiopian Restaurant","Brazilian Churrascaria","French Patisserie",
            "Waffle House","Pancake House","Brunch Spot","Late Night Diner","Sports Bar",
            "Rooftop Bar","Beach Bar","Tiki Bar","Jazz Bar","Comedy Club","Karaoke Bar",
            "Night Club","Disco","Lounge","Cocktail Bar","Speakeasy","Irish Pub",
            "British Pub","Tapas Bar","Wine Bar","Cigar Lounge","Hookah Lounge",
            "Pool Hall","Arcade","Escape Room","Laser Tag Arena","Paintball Field",
            "Go-Kart Track","Mini Golf","Rock Climbing Wall","Trampoline Park",
            "Indoor Skydiving","Virtual Reality Arcade","Board Game Cafe","Bookstore Cafe",
            "Art Gallery","Photography Studio","Recording Studio","Film Studio",
            "Theater","Opera House","Concert Hall","Jazz Club","Live Music Venue",
            "Comedy Club","Magic Show","Circus","Carnival","Fair","Festival Grounds",
            "Convention Center","Exhibition Hall","Trade Show","Conference Center",
            "Business Center","Coworking Space","Office Building","Skyscraper",
            "Factory","Warehouse","Distribution Center","Shipping Port","Container Yard",
            "Railway Yard","Bus Depot","Taxi Stand","Rideshare Hub","Parking Lot",
            "Parking Garage","Gas Station","Car Wash","Auto Repair Shop","Tire Shop",
            "Car Dealership","Used Car Lot","Junkyard","Salvage Yard","Recycling Center",
            "Waste Management","Power Plant","Solar Farm","Wind Farm","Dam","Reservoir",
            "Water Treatment Plant","Sewage Plant","Oil Refinery","Chemical Plant",
            "Coal Mine","Gold Mine","Diamond Mine","Salt Mine","Quarry","Construction Site",
            "Demolition Site","Lumber Yard","Sawmill","Paper Mill","Textile Factory",
            "Shoe Factory","Electronics Factory","Car Factory","Airplane Hangar",
            "Military Base","Army Camp","Naval Base","Air Force Base","Coast Guard Station",
            "Police Station","Fire Station","Ambulance Station","Hospital","Clinic",
            "Doctor's Office","Dentist Office","Eye Doctor","Chiropractor","Physiotherapy",
            "Mental Health Clinic","Rehabilitation Center","Nursing Home","Retirement Home",
            "Assisted Living","Orphanage","Foster Home","Shelter","Food Bank",
            "Community Center","Recreation Center","Senior Center","Youth Center",
            "Day Care","Kindergarten","Elementary School","Middle School","High School",
            "Vocational School","Community College","University","Graduate School",
            "Law School","Medical School","Business School","Art School","Music School",
            "Drama School","Film School","Culinary School","Nursing School","Seminary",
            "Monastery","Convent","Church","Cathedral","Chapel","Synagogue","Temple",
            "Hindu Temple","Buddhist Temple","Shinto Shrine","Mosque","Madrasa",
            "Sufi Lodge","Meditation Center","Retreat Center","Ashram","Yoga Retreat",
            "Spa Resort","Wellness Center","Detox Center","Addiction Clinic","Prison",
            "Jail","Detention Center","Courthouse","Law Office","Government Building",
            "City Hall","Town Hall","Parliament","Senate","Congress","Embassy",
            "Consulate","Immigration Office","Post Office","Bank","Credit Union",
            "ATM","Stock Exchange","Insurance Office","Real Estate Office","Notary",
            "Tax Office","Social Security Office","Unemployment Office","DMV",
            "Library","Archive","Records Office","Museum","History Museum","Science Museum",
            "Natural History Museum","Art Museum","Children's Museum","Wax Museum",
            "Maritime Museum","Military Museum","Space Museum","Technology Museum",
            "Film Museum","Music Museum","Sports Hall of Fame","Hall of Records",
            "National Park","State Park","City Park","Botanical Garden","Rose Garden",
            "Japanese Garden","Zen Garden","Community Garden","Rooftop Garden",
            "Greenhouse","Nursery","Tree Farm","Orchard","Vineyard","Winery","Brewery",
            "Distillery","Cidery","Meadery","Dairy Farm","Egg Farm","Poultry Farm",
            "Pig Farm","Cattle Ranch","Sheep Farm","Goat Farm","Horse Ranch","Stable",
            "Racetrack","Rodeo Arena","Bull Ring","Cockfighting Pit","Dog Track",
            "Camel Racing Track","Polo Club","Equestrian Center","Petting Zoo",
            "Animal Shelter","Veterinary Clinic","Pet Store","Bird Sanctuary",
            "Wildlife Reserve","Game Reserve","Safari Park","Elephant Sanctuary",
            "Tiger Reserve","Wolf Sanctuary","Bear Sanctuary","Dolphin Center",
            "Whale Watching Spot","Shark Dive Site","Coral Reef","Underwater Cave",
            "Sea Cave","Glacier","Iceberg","Arctic Tundra","Antarctic Station",
            "Volcanic Island","Hot Spring","Geyser","Waterfall","Canyon","Gorge",
            "Cliff","Cave System","Stalactite Cave","Crystal Cave","Salt Flat",
            "Sand Dunes","Oasis","Jungle","Rainforest","Cloud Forest","Bamboo Forest",
            "Pine Forest","Redwood Forest","Mangrove Swamp","Wetland","Marsh",
            "Peat Bog","Prairie","Savanna","Steppe","Tundra","Taiga","Biome Center",
            "Ecological Reserve","Marine Reserve","Coral Sanctuary","Tide Pool",
            "Lighthouse","Coast Guard Tower","Watchtower","Observation Deck",
            "Radio Tower","Cell Tower","TV Station","Radio Station","Newspaper Office",
            "Magazine Office","Online News Hub","Press Room","Broadcast Studio",
            "Podcast Studio","YouTube Studio","Streaming Center","Data Center",
            "Server Farm","Satellite Station","Space Center","Launch Pad","Mission Control",
            "Observatory","Planetarium","Science Center","Research Lab","Think Tank",
            "Startup Hub","Tech Campus","Silicon Valley Office","Innovation Lab",
            "Maker Space","Hack Space","Fab Lab","3D Printing Center","Robotics Lab",
            "AI Research Center","Biotech Lab","Pharmaceutical Plant","Clean Room",
            "Nuclear Facility","Particle Accelerator","Wind Tunnel","Crash Test Facility",
            "Shooting Range","Archery Range","Fencing Club","Wrestling Gym","Judo Dojo",
            "Karate Dojo","Taekwondo Dojo","Boxing Ring","MMA Cage","Weightlifting Gym",
            "CrossFit Box","Pilates Studio","Aerial Silk Studio","Circus School",
            "Trapeze School","Parkour Gym","Ninja Warrior Course","Obstacle Course",
            "Mud Run Course","Zip Line Park","Bungee Jump Site","Skydiving Center",
            "Hang Gliding Launch","Paragliding Hill","Hot Air Balloon Launch",
            "Helicopter Pad","Private Airport","International Airport","Regional Airport",
            "Seaplane Base","Cruise Terminal","Ferry Terminal","Marina","Yacht Club",
            "Fishing Pier","Boardwalk","Promenade","Pier","Jetty","Breakwater",
            "Harbor","Bay","Cove","Lagoon","Atoll","Reef","Sandbar","Delta",
            "Estuary","Fjord","Strait","Sound","Gulf","Sea","Ocean","Lake",
            "Pond","Stream","River","Creek","Waterfall","Hot Spring","Geyser",
            "Volcano","Crater","Caldera","Lava Field","Obsidian Plain","Pumice Field",
            "Glacier Valley","Ice Cave","Snow Field","Ski Resort","Ski Lodge",
            "Mountain Hut","Alpine Refuge","Basecamp","Summit","Ridge","Pass",
            "Valley","Plateau","Mesa","Butte","Arch","Natural Bridge","Rock Formation",
            "Badlands","Monument Valley","Grand Canyon","Victoria Falls","Niagara Falls",
            "Amazon Jungle","Congo Basin","Nile Delta","Sahara Desert","Gobi Desert",
            "Australian Outback","New Zealand Fjord","Norwegian Fjord","Scottish Highlands",
            "Italian Riviera","French Countryside","Spanish Coast","Greek Islands",
            "Turkish Coast","Croatian Islands","Adriatic Sea","Mediterranean Sea",
            "Caribbean Island","Tropical Island","Remote Island","Deserted Island",
            "Inhabited Island","Island Resort","Overwater Bungalow","Treehouse Hotel",
            "Cave Hotel","Ice Hotel","Underwater Hotel","Castle Hotel","Palace Hotel",
            "Boutique Hotel","Budget Hostel","Backpacker Lodge","Camping Site",
            "Glamping Site","RV Park","Caravan Park","Mobile Home Park","Trailer Park"
    };

    // ── FOOD & DRINKS (500+) ──────────────────────────────────────────────────
    private static final String[] FOOD = {
            "Pizza","Burger","Tacos","Sandwich","Fries","Chicken","Kebab","Couscous",
            "Tagine","Harira","Pastilla","Rfissa","Olives","Dates","Orange","Banana",
            "Apple","Watermelon","Avocado","Mint Tea","Coffee","Juice","Soda","Milk",
            "Chocolate","Cake","Ice Cream","Croissant","Pancake","Waffle","Soup",
            "Salad","Rice","Pasta","Cheese","Egg","Steak","Fish","Shrimp","Lemon",
            "Strawberry","Peach","Grapes","Almond","Peanut","Honey","Jam","Butter",
            "Bread","Baguette","Bagel","Pretzel","Cracker","Tortilla","Pita","Naan",
            "Chapati","Roti","Injera","Fufu","Ugali","Plantain","Yam","Cassava",
            "Sweet Potato","Potato","Mashed Potato","Potato Salad","French Onion Soup",
            "Minestrone","Tomato Soup","Chicken Noodle Soup","Ramen","Pho","Laksa",
            "Tom Yum","Miso Soup","Hot Pot","Fondue","Raclette","Quiche","Frittata",
            "Omelette","Scrambled Eggs","Poached Eggs","Fried Eggs","Eggs Benedict",
            "French Toast","Crepe","Blini","Waffles","Belgian Waffle","Churros",
            "Donut","Muffin","Scone","Biscuit","Cookie","Brownie","Blondie","Bar",
            "Cupcake","Layer Cake","Cheesecake","Tart","Pie","Cobbler","Crisp",
            "Crumble","Pudding","Custard","Creme Brulee","Panna Cotta","Tiramisu",
            "Cannoli","Eclair","Macaron","Profiterole","Beignet","Churro","Churros",
            "Baklava","Knafeh","Halva","Turkish Delight","Mochi","Daifuku","Wagashi",
            "Matcha","Bubble Tea","Chai","Espresso","Americano","Latte","Cappuccino",
            "Flat White","Macchiato","Cold Brew","Nitro Coffee","Affogato","Irish Coffee",
            "Hot Chocolate","Mulled Wine","Eggnog","Horchata","Lassi","Kefir","Kombucha",
            "Lemonade","Iced Tea","Arnold Palmer","Virgin Mojito","Smoothie","Milkshake",
            "Frappe","Slushie","Energy Drink","Sports Drink","Coconut Water","Sparkling Water",
            "Tonic Water","Ginger Ale","Root Beer","Cream Soda","Orange Soda","Cola",
            "Beer","Lager","Ale","Stout","Porter","IPA","Wheat Beer","Sour Beer",
            "Wine","Red Wine","White Wine","Rosé Wine","Champagne","Prosecco","Cava",
            "Sangria","Mulled Wine","Port","Sherry","Vermouth","Sake","Soju","Makgeolli",
            "Vodka","Gin","Rum","Tequila","Mezcal","Whiskey","Bourbon","Scotch",
            "Brandy","Cognac","Armagnac","Calvados","Pisco","Cachaca","Arrack",
            "Mojito","Margarita","Daiquiri","Cosmopolitan","Negroni","Martini",
            "Old Fashioned","Manhattan","Whiskey Sour","Tom Collins","Gin Tonic",
            "Moscow Mule","Dark and Stormy","Paloma","Aperol Spritz","Bellini",
            "Mimosa","Bloody Mary","Tequila Sunrise","Long Island Iced Tea","Piña Colada",
            "Mai Tai","Hurricane","Singapore Sling","Clover Club","Last Word",
            "Spaghetti","Fettuccine","Linguine","Penne","Rigatoni","Farfalle",
            "Fusilli","Orzo","Gnocchi","Ravioli","Tortellini","Lasagna","Cannelloni",
            "Carbonara","Bolognese","Amatriciana","Cacio e Pepe","Pesto","Marinara",
            "Arrabbiata","Vodka Sauce","Alfredo","Primavera","Putanesca","Aglio e Olio",
            "Risotto","Polenta","Osso Buco","Saltimbocca","Piccata","Parmigiana",
            "Caprese","Bruschetta","Antipasto","Prosciutto","Salami","Mortadella",
            "Bresaola","Pancetta","Guanciale","Nduja","Porchetta","Arancini","Suppli",
            "Sushi","Sashimi","Maki","Nigiri","Temaki","Chirashi","Donburi","Gyudon",
            "Oyakodon","Karaage","Tonkatsu","Yakitori","Teriyaki","Sukiyaki","Shabu Shabu",
            "Tempura","Edamame","Takoyaki","Okonomiyaki","Udon","Soba","Yakisoba",
            "Onigiri","Bento","Miso","Tofu","Natto","Kimchi","Bibimbap","Japchae",
            "Bulgogi","Galbi","Sundubu","Doenjang","Gochujang","Tteokbokki","Samgyeopsal",
            "Banh Mi","Spring Roll","Summer Roll","Pho","Bun Bo Hue","Cao Lau",
            "Banh Xeo","Che","Com Tam","Nem Cuon","Goi Cuon","Hu Tieu",
            "Pad Thai","Tom Kha","Som Tum","Massaman Curry","Green Curry","Red Curry",
            "Yellow Curry","Panang Curry","Khao Pad","Mango Sticky Rice","Satay",
            "Rendang","Nasi Goreng","Mie Goreng","Gado Gado","Soto","Gulai","Opor",
            "Nasi Lemak","Laksa","Char Kway Teow","Hainanese Chicken Rice","Chili Crab",
            "Roti Canai","Dum Biryani","Butter Chicken","Tikka Masala","Palak Paneer",
            "Dal","Chana Masala","Aloo Gobi","Samosa","Pakora","Bhel Puri","Pani Puri",
            "Dosa","Idli","Vada","Uttapam","Paratha","Chole Bhature","Rajma","Kadhi",
            "Kheer","Gulab Jamun","Jalebi","Barfi","Rasgulla","Ladoo","Halwa",
            "Shawarma","Falafel","Hummus","Baba Ganoush","Tabbouleh","Fattoush",
            "Kibbeh","Kofta","Mansaf","Kabsa","Machboos","Harees","Jareesh",
            "Mutabbaq","Luqaimat","Om Ali","Basbousa","Kunafa","Qatayef",
            "Paella","Tortilla Española","Gazpacho","Croquetas","Patatas Bravas",
            "Jamon","Chorizo","Morcilla","Pulpo a Gallega","Fabada","Cocido",
            "Bouillabaisse","Ratatouille","Cassoulet","Coq au Vin","Boeuf Bourguignon",
            "Quiche Lorraine","Salade Nicoise","Croque Monsieur","Soupe à l'oignon",
            "Beef Stew","Pot Roast","Meatloaf","Meatballs","Meatball Sub","Sloppy Joe",
            "Hot Dog","Corn Dog","Bratwurst","Kielbasa","Sausage Roll","Pigs in Blankets",
            "Yorkshire Pudding","Shepherd's Pie","Cottage Pie","Bangers and Mash",
            "Fish and Chips","Chicken Tikka Masala","Chicken Korma","Beef Wellington",
            "Haggis","Scotch Egg","Welsh Rarebit","Cornish Pasty","Eton Mess",
            "Sticky Toffee Pudding","Trifle","Victoria Sponge","Scones with Clotted Cream",
            "Wurst","Schnitzel","Sauerkraut","Pretzels","Black Forest Cake","Strudel",
            "Jagerschnitzel","Currywurst","Kasespaetzle","Maultaschen","Lebkuchen",
            "Pierogi","Borscht","Goulash","Schnitzel","Pelmeni","Blini with Caviar",
            "Beef Stroganoff","Chicken Kiev","Holodets","Solyanka","Okroshka",
            "Ceviche","Empanada","Arepa","Tamale","Pozole","Enchilada","Burrito",
            "Quesadilla","Nachos","Guacamole","Salsa","Pico de Gallo","Mole",
            "Churrasco","Feijoada","Brigadeiro","Pão de Queijo","Coxinha","Acarajé",
            "Injera","Doro Wat","Kitfo","Tibs","Shiro","Misir","Ful Medames",
            "Jollof Rice","Suya","Egusi Soup","Fufu","Ogbono Soup","Puff Puff",
            "Biltong","Bobotie","Bunny Chow","Boerewors","Koeksisters","Malva Pudding"
    };

    // ── TECH & INTERNET (500+) ────────────────────────────────────────────────
    private static final String[] TECH = {
            "Instagram","TikTok","YouTube","WhatsApp","Snapchat","Facebook","WiFi",
            "Password","Application","Video Game","PlayStation","Xbox","Netflix",
            "Spotify","Google","Email","Website","Screenshot","Emoji","Meme",
            "Influencer","Stream","Podcast","Server","Cloud","USB Drive","Hard Drive",
            "Touchscreen","Smartwatch","Drone","Virtual Reality","Artificial Intelligence",
            "Robot","Code","Hacker","Algorithm","API","App Store","Augmented Reality",
            "Autoplay","Avatar","Backup","Bandwidth","Beta Version","Blockchain",
            "Blog","Bluetooth","Boot","Browser","Bug","Cache","Chatbot","Chatroom",
            "Chip","Click","Coding","Command Line","Cookie","CPU","Crash","Cursor",
            "Cybersecurity","Dashboard","Data","Database","Debugging","Deep Learning",
            "Desktop","Developer","Digital Wallet","Domain","Download","Encryption",
            "File","Filter","Firewall","Firmware","Folder","Forum","Framework",
            "Frontend","Backend","Full Stack","GIF","GPU","Graphics Card","Hashtag",
            "HTML","HTTP","HTTPS","Hyperlink","Icon","IDE","Interface","Internet",
            "IP Address","JavaScript","JSON","Kernel","Keyboard Shortcut","Lag",
            "LAN","Laptop","Latency","Linux","Loading","Login","Logout","Loop",
            "Machine Learning","Malware","Memory","Metadata","Mobile App","Modem",
            "Monitor","Motherboard","Mouse Click","Network","Notification","Object",
            "Open Source","Operating System","Optimization","Patch","Payload","Pixel",
            "Plugin","Popup","Port","Privacy","Processor","Profile","Program","Protocol",
            "Python","Query","RAM","Rendering","Repository","Resolution","Runtime",
            "Script","Search Engine","Security","Selfie","Social Media","Software",
            "Source Code","Spam","Storage","Streaming","String","Subdomain","Syntax",
            "Terminal","Thread","Token","Toolbar","Tooltip","UI","UX","Update","Upload",
            "URL","User","Variable","Version","Virus","Vulnerability","WAN","Web App",
            "Webhook","Wi-Fi Password","Windows","XML","Zero-Day","Zoom","Tweet",
            "Repost","Viral","Trending","Follower","Following","Like","Share","Comment",
            "Story","Reel","Live","Bio","Handle","Tag","Mention","DM","Group Chat",
            "Sticker","Voice Note","Video Call","Conference Call","Screen Share",
            "Reaction","Poll","Survey","Form","Spreadsheet","Document","Presentation",
            "Calendar","Reminder","Notification Badge","Dark Mode","Light Mode",
            "Night Mode","Do Not Disturb","Airplane Mode","Battery Saver","Data Plan",
            "Hotspot","Tethering","VPN","Proxy","Tor","Dark Web","Deep Web","Forum Post",
            "Subreddit","Thread","Upvote","Downvote","Karma","Mod","Ban","Shadowban",
            "Verified","Blue Tick","Verification Code","Two-Factor Auth","Biometric Login",
            "Face ID","Fingerprint Scanner","Pin Code","Captcha","QR Code","Barcode",
            "NFC","RFID","Bluetooth Pairing","Syncing","Backup","Restore","Factory Reset",
            "Software Update","System Update","Driver Update","Firmware Update","Patch",
            "Bug Fix","Hotfix","Rollback","Version Control","Git","GitHub","GitLab",
            "Bitbucket","Commit","Branch","Merge","Pull Request","Fork","Clone","Push",
            "Deployment","CI/CD","Docker","Container","Kubernetes","Microservice",
            "Lambda","Serverless","Cloud Function","S3 Bucket","EC2","Azure","GCP",
            "Firebase","Heroku","Netlify","Vercel","Cloudflare","Nginx","Apache",
            "Load Balancer","CDN","DNS","SSL Certificate","HTTPS Redirect","Subdomain",
            "Webhook","REST API","GraphQL","SOAP","gRPC","WebSocket","OAuth","JWT",
            "Session","Cookie","LocalStorage","IndexedDB","Redux","State Management",
            "React","Vue","Angular","Svelte","Next.js","Nuxt.js","Remix","Astro",
            "Node.js","Deno","Bun","Express","FastAPI","Django","Flask","Rails","Laravel",
            "Spring Boot","Hibernate","Sequelize","Prisma","MongoDB","PostgreSQL",
            "MySQL","SQLite","Redis","Elasticsearch","Kafka","RabbitMQ","Celery",
            "Cron Job","Batch Processing","ETL","Data Pipeline","Data Warehouse",
            "Data Lake","Spark","Hadoop","Hive","Pig","Airflow","dbt","Tableau",
            "Power BI","Grafana","Prometheus","Datadog","Splunk","ELK Stack",
            "Terraform","Ansible","Puppet","Chef","Jenkins","CircleCI","GitHub Actions",
            "Selenium","Cypress","Jest","Mocha","Chai","JUnit","PyTest","Postman",
            "Swagger","OpenAPI","Insomnia","Curl","Bash Script","PowerShell Script",
            "Python Script","Ruby Script","Shell Script","Makefile","Dockerfile",
            "YAML","TOML","ENV File","Config File","Dotenv","Secret Manager","Vault",
            "IAM Role","Policy","Permission","Access Control","Audit Log","Compliance",
            "GDPR","CCPA","HIPAA","SOC 2","ISO 27001","Penetration Test","Bug Bounty",
            "Phishing","Social Engineering","Ransomware","Keylogger","Trojan","Spyware",
            "Adware","Botnet","DDoS","Man in the Middle","SQL Injection","XSS","CSRF",
            "Buffer Overflow","Zero-Day Exploit","Patch Tuesday","Vulnerability Scan",
            "Antivirus","Firewall Rule","Intrusion Detection","Honeypot","Sandbox",
            "Virtual Machine","Hypervisor","Emulator","Simulator","Debugger","Profiler",
            "Memory Leak","Race Condition","Deadlock","Thread Pool","Async","Await",
            "Promise","Callback","Event Loop","Garbage Collection","Heap","Stack",
            "Recursion","Iteration","Big O","Time Complexity","Space Complexity",
            "Binary Search","Bubble Sort","Quick Sort","Merge Sort","Hash Table",
            "Binary Tree","Linked List","Queue","Deque","Graph","Dijkstra","BFS","DFS",
            "Dynamic Programming","Greedy Algorithm","Backtracking","Divide and Conquer",
            "Design Pattern","Singleton","Factory","Observer","MVC","MVVM","MVP",
            "Dependency Injection","Inversion of Control","SOLID Principles","DRY",
            "KISS","YAGNI","Agile","Scrum","Kanban","Sprint","Retrospective","Standup",
            "Pair Programming","Code Review","Technical Debt","Refactoring","Legacy Code",
            "Unit Test","Integration Test","End-to-End Test","Load Test","Stress Test",
            "A/B Test","Feature Flag","Canary Release","Blue Green Deployment",
            "Monolith","Microservices","Service Mesh","API Gateway","Event Driven",
            "Message Queue","Pub Sub","CQRS","Event Sourcing","Domain Driven Design"
    };

    // ── ANIMALS (500+) ────────────────────────────────────────────────────────
    private static final String[] ANIMALS = {
            "Cat","Dog","Lion","Tiger","Horse","Cow","Camel","Sheep","Goat",
            "Monkey","Elephant","Snake","Eagle","Falcon","Shark","Fish","Chicken",
            "Donkey","Rabbit","Wolf","Fox","Bear","Giraffe","Zebra","Panda",
            "Cheetah","Dolphin","Whale","Alligator","Crocodile","Hippopotamus",
            "Rhinoceros","Gorilla","Chimpanzee","Baboon","Orangutan","Lemur","Sloth",
            "Anteater","Armadillo","Pangolin","Echidna","Platypus","Wombat","Koala",
            "Kangaroo","Wallaby","Quokka","Tasmanian Devil","Dingo","Cassowary","Emu",
            "Kiwi","Tuatara","Komodo Dragon","Monitor Lizard","Iguana","Gecko",
            "Chameleon","Anole","Skink","Salamander","Newt","Axolotl","Frog",
            "Toad","Tree Frog","Poison Dart Frog","Bullfrog","Caecilian","Mudpuppy",
            "Python","Boa Constrictor","Anaconda","King Cobra","Black Mamba","Viper",
            "Rattlesnake","Copperhead","Cottonmouth","Coral Snake","Garter Snake",
            "Corn Snake","Ball Python","Milk Snake","Kingsnake","Hognose Snake",
            "Sea Snake","Tree Snake","Flying Snake","Blind Snake","Worm Snake",
            "Sea Turtle","Loggerhead Turtle","Leatherback Turtle","Green Turtle",
            "Hawksbill Turtle","Flatback Turtle","Ridley Turtle","Snapping Turtle",
            "Painted Turtle","Box Turtle","Tortoise","Galapagos Tortoise",
            "Aldabra Tortoise","Radiated Tortoise","Ploughshare Tortoise",
            "Parrot","Macaw","Cockatoo","Cockatiel","Parakeet","Lovebird","Budgerigar",
            "African Grey","Amazon Parrot","Eclectus","Lorikeet","Conure","Caique",
            "Toucan","Hornbill","Pelican","Flamingo","Peacock","Turkey","Pheasant",
            "Quail","Grouse","Partridge","Guinea Fowl","Peafowl","Crane","Stork",
            "Heron","Egret","Ibis","Spoonbill","Shoebill","Marabou Stork","Jabiru",
            "Vulture","Condor","Osprey","Hawk","Kite","Harrier","Buzzard","Kestrel",
            "Merlin","Hobby","Goshawk","Sparrowhawk","Peregrine","Barn Owl","Snowy Owl",
            "Great Horned Owl","Tawny Owl","Burrowing Owl","Screech Owl","Elf Owl",
            "Penguin","Puffin","Albatross","Petrel","Shearwater","Booby","Gannet",
            "Frigatebird","Tropicbird","Skua","Jaeger","Tern","Gull","Kittiwake",
            "Auk","Murre","Razorbill","Dovekie","Cormorant","Anhinga","Sunbittern",
            "Hummingbird","Swift","Martin","Swallow","Kingfisher","Bee-eater","Roller",
            "Hoopoe","Woodpecker","Wryneck","Piculet","Jacamar","Barbet","Toucanet",
            "Honeyguide","Broadbill","Pitta","Lyrebird","Riflebird","Bird-of-Paradise",
            "Bowerbird","Manakin","Cotinga","Antbird","Tapaculo","Gnateater","Antthrush",
            "Thrush","Robin","Blackbird","Song Thrush","Nightingale","Wheatear","Stonechat",
            "Bluebird","Redstart","Flycatcher","Wagtail","Pipit","Lark","Finch","Sparrow",
            "Bunting","Warbler","Vireo","Tanager","Cardinal","Grosbeak","Crossbill",
            "Siskin","Goldfinch","Greenfinch","Hawfinch","Bullfinch","Jay","Magpie",
            "Crow","Raven","Jackdaw","Rook","Nutcracker","Chough","Starling","Myna",
            "Oriole","Drongo","Fantail","Monarch","Iora","Cuckoo","Coucal","Roadrunner",
            "Ani","Nightjar","Potoo","Frogmouth","Oilbird","Dove","Pigeon","Sandgrouse",
            "Lion Fish","Clown Fish","Blue Tang","Angel Fish","Butterfly Fish","Puffer Fish",
            "Trigger Fish","Surgeon Fish","Damselfish","Wrasse","Grouper","Snapper",
            "Barracuda","Manta Ray","Stingray","Electric Ray","Swordfish","Marlin",
            "Tuna","Wahoo","Mahi Mahi","Sailfish","Tarpon","Bonefish","Permit",
            "Carp","Trout","Salmon","Bass","Pike","Perch","Catfish","Eel","Moray Eel",
            "Hagfish","Lamprey","Coelacanth","Lungfish","Sturgeon","Paddlefish",
            "Arapaima","Piranha","Pacú","Tambaqui","Piraiba","Goliath Tiger Fish",
            "Octopus","Squid","Cuttlefish","Nautilus","Chambered Nautilus","Nudibranch",
            "Sea Slug","Clam","Oyster","Scallop","Mussel","Whelk","Conch","Abalone",
            "Chiton","Snail","Slug","Earthworm","Leech","Centipede","Millipede",
            "Scorpion","Spider","Tarantula","Jumping Spider","Wolf Spider","Orb Weaver",
            "Crab Spider","Trapdoor Spider","Funnel Web","Redback Spider","Black Widow",
            "Brown Recluse","Harvestman","Tick","Mite","Horseshoe Crab","Sea Spider",
            "Crab","Lobster","Crayfish","Shrimp","Prawn","Krill","Barnacle",
            "Isopod","Amphipod","Copepod","Ostracod","Water Flea","Fairy Shrimp",
            "Bee","Wasp","Hornet","Bumblebee","Honey Bee","Carpenter Bee","Mason Bee",
            "Leafcutter Bee","Sweat Bee","Ant","Fire Ant","Army Ant","Leafcutter Ant",
            "Bullet Ant","Driver Ant","Harvester Ant","Carpenter Ant","Termite",
            "Butterfly","Moth","Hawk Moth","Luna Moth","Atlas Moth","Monarch Butterfly",
            "Swallowtail","Painted Lady","Blue Morpho","Birdwing","Skipper","Dragonfly",
            "Damselfly","Mayfly","Stonefly","Lacewing","Antlion","Dobsonfly","Alderfly",
            "Firefly","Glowworm","Beetle","Ladybug","Weevil","Longhorn Beetle","Dung Beetle",
            "Bombardier Beetle","Stag Beetle","Rhinoceros Beetle","Hercules Beetle",
            "Grasshopper","Cricket","Katydid","Locust","Stick Insect","Leaf Insect",
            "Praying Mantis","Cockroach","Earwig","Silverfish","Springtail","Thrips",
            "Whitefly","Aphid","Scale Insect","Mealybug","Leafhopper","Planthopper",
            "Cicada","Assassin Bug","Stink Bug","Water Strider","Water Boatman",
            "Giant Water Bug","Backswimmer","Diving Beetle","Whirligig Beetle"
            ,
            // Additional animals
            "Firefly","Glowworm","Bombardier Beetle","Stag Beetle","Rhinoceros Beetle",
            "Hercules Beetle","Dung Beetle","Ladybug","Weevil","Longhorn Beetle",
            "Grasshopper","Cricket","Katydid","Locust","Stick Insect","Leaf Insect",
            "Praying Mantis","Cockroach","Earwig","Silverfish","Cicada","Water Strider",
            "Bee","Bumblebee","Honey Bee","Carpenter Bee","Wasp","Hornet","Fire Ant",
            "Army Ant","Leafcutter Ant","Termite","Butterfly","Monarch Butterfly",
            "Swallowtail","Blue Morpho","Painted Lady","Hawk Moth","Luna Moth",
            "Atlas Moth","Dragonfly","Damselfly","Mayfly","Lacewing","Antlion",
            "Manta Ray","Stingray","Swordfish","Marlin","Tuna","Sailfish","Barracuda",
            "Clown Fish","Angel Fish","Puffer Fish","Lionfish","Grouper","Snapper",
            "Carp","Trout","Salmon","Bass","Pike","Catfish","Eel","Moray Eel",
            "Octopus","Squid","Cuttlefish","Nautilus","Sea Slug","Nudibranch",
            "Clam","Oyster","Scallop","Mussel","Abalone","Snail","Earthworm","Leech",
            "Centipede","Millipede","Scorpion","Tarantula","Wolf Spider","Black Widow",
            "Brown Recluse","Jumping Spider","Orb Weaver","Horseshoe Crab",
            "Lobster","Crayfish","Barnacle","Krill","Sea Urchin","Starfish",
            "Jellyfish","Sea Anemone","Coral","Sea Horse","Sea Dragon","Axolotl"
    };

    // ── JOBS & PROFESSIONS (500+) ─────────────────────────────────────────────
    private static final String[] JOBS = {
            "Doctor","Nurse","Teacher","Engineer","Architect","Police Officer","Soldier",
            "Chef","Driver","Pilot","Programmer","Designer","Photographer","Mechanic",
            "Electrician","Barber","Farmer","Journalist","Actor","Singer","Athlete",
            "Referee","Coach","Business Owner","Lawyer","Dentist","Pharmacist","Firefighter",
            "Surgeon","Anesthesiologist","Radiologist","Cardiologist","Neurologist",
            "Oncologist","Pediatrician","Dermatologist","Ophthalmologist","Orthopedist",
            "Psychiatrist","Psychologist","Therapist","Counselor","Social Worker",
            "Occupational Therapist","Physical Therapist","Speech Therapist","Dietitian",
            "Nutritionist","Chiropractor","Osteopath","Acupuncturist","Midwife","Doula",
            "Paramedic","EMT","ER Nurse","ICU Nurse","OR Nurse","Scrub Nurse",
            "Nurse Practitioner","Physician Assistant","Medical Assistant","Lab Technician",
            "Radiologist Technician","Phlebotomist","Respiratory Therapist","Audiologist",
            "Optometrist","Orthodontist","Periodontist","Endodontist","Oral Surgeon",
            "Prosthodontist","Dental Hygienist","Dental Assistant","Veterinarian",
            "Vet Technician","Animal Control Officer","Zoo Keeper","Wildlife Biologist",
            "Marine Biologist","Ecologist","Botanist","Zoologist","Entomologist",
            "Ornithologist","Ichthyologist","Herpetologist","Mammalogist","Paleontologist",
            "Geologist","Mineralogist","Vulcanologist","Seismologist","Meteorologist",
            "Climatologist","Oceanographer","Hydrologist","Soil Scientist","Agronomist",
            "Horticulturist","Forester","Park Ranger","Conservation Officer","Game Warden",
            "Fish and Wildlife Officer","Border Patrol Agent","Customs Officer",
            "Immigration Officer","FBI Agent","CIA Analyst","NSA Analyst","DEA Agent",
            "ATF Agent","Secret Service Agent","Air Marshal","SWAT Officer","Detective",
            "Forensic Scientist","Crime Scene Investigator","Forensic Accountant",
            "Forensic Psychologist","Criminal Profiler","Polygraph Examiner",
            "Bail Bondsman","Private Investigator","Security Guard","Bodyguard",
            "Loss Prevention Officer","Armed Guard","Night Watchman","Bouncer",
            "Judge","Prosecutor","Defense Attorney","Public Defender","Paralegal",
            "Legal Secretary","Law Clerk","Court Reporter","Bailiff","Mediator",
            "Arbitrator","Patent Attorney","Immigration Lawyer","Tax Attorney",
            "Real Estate Attorney","Corporate Lawyer","Environmental Lawyer",
            "Human Rights Lawyer","Civil Rights Lawyer","Family Lawyer","Divorce Attorney",
            "Criminal Defense Lawyer","Intellectual Property Lawyer","Maritime Lawyer",
            "Notary Public","Title Agent","Escrow Officer","Mortgage Broker",
            "Real Estate Agent","Property Manager","Building Inspector","Appraiser",
            "Urban Planner","Land Surveyor","Civil Engineer","Structural Engineer",
            "Mechanical Engineer","Electrical Engineer","Chemical Engineer","Aerospace Engineer",
            "Nuclear Engineer","Petroleum Engineer","Mining Engineer","Marine Engineer",
            "Environmental Engineer","Biomedical Engineer","Robotics Engineer",
            "Software Engineer","Hardware Engineer","Network Engineer","Systems Engineer",
            "DevOps Engineer","Data Engineer","Machine Learning Engineer","AI Researcher",
            "Data Scientist","Business Analyst","Systems Analyst","Financial Analyst",
            "Investment Banker","Portfolio Manager","Hedge Fund Manager","Trader",
            "Stockbroker","Financial Advisor","Wealth Manager","Insurance Agent",
            "Actuary","Auditor","Accountant","CPA","Tax Preparer","Bookkeeper",
            "Payroll Specialist","Purchasing Agent","Supply Chain Manager","Logistics Manager",
            "Warehouse Manager","Inventory Manager","Operations Manager","Project Manager",
            "Product Manager","Program Manager","Scrum Master","Agile Coach",
            "Marketing Manager","Brand Manager","Content Manager","Social Media Manager",
            "SEO Specialist","PPC Specialist","Email Marketer","Affiliate Marketer",
            "Copywriter","Content Writer","Technical Writer","Grant Writer","Speechwriter",
            "Editor","Proofreader","Translator","Interpreter","Linguist","Librarian",
            "Archivist","Curator","Museum Director","Art Director","Creative Director",
            "Graphic Designer","Illustrator","Animator","Motion Designer","3D Artist",
            "VFX Artist","Game Designer","Level Designer","UX Designer","UI Designer",
            "Product Designer","Industrial Designer","Fashion Designer","Textile Designer",
            "Interior Designer","Interior Decorator","Set Designer","Costume Designer",
            "Makeup Artist","Hair Stylist","Nail Technician","Esthetician","Massage Therapist",
            "Personal Trainer","Yoga Instructor","Pilates Instructor","Aerobics Instructor",
            "Swimming Coach","Tennis Coach","Golf Instructor","Ski Instructor","Surf Instructor",
            "Rock Climbing Instructor","Diving Instructor","Flight Instructor",
            "Driving Instructor","Music Teacher","Art Teacher","Drama Teacher","Dance Teacher",
            "Tutor","Academic Coach","School Counselor","Special Education Teacher",
            "ESL Teacher","Professor","Lecturer","Research Scientist","Postdoctoral Researcher",
            "Lab Manager","Clinical Researcher","Epidemiologist","Biostatistician",
            "Public Health Official","Health Inspector","Food Safety Inspector",
            "Building Code Inspector","Fire Inspector","Environmental Inspector",
            "Occupational Safety Inspector","Quality Control Inspector","Product Tester",
            "Chef de Cuisine","Sous Chef","Pastry Chef","Line Cook","Prep Cook",
            "Short Order Cook","Sushi Chef","Butcher","Baker","Pastry Artist",
            "Cake Decorator","Chocolatier","Barista","Sommelier","Mixologist","Bartender",
            "Waiter","Waitress","Host","Maitre D","Busboy","Food Runner","Caterer",
            "Event Planner","Wedding Planner","Party Planner","Conference Organizer",
            "Stage Manager","Event Coordinator","Venue Manager","DJ","MC","Emcee",
            "Comedian","Magician","Clown","Juggler","Acrobat","Contortionist","Stuntman",
            "Voice Actor","Narrator","Audiobook Reader","Podcast Host","Radio Host",
            "TV Host","News Anchor","Sports Commentator","Weather Forecaster","Traffic Reporter",
            "Photojournalist","Videographer","Cinematographer","Camera Operator","Gaffer",
            "Key Grip","Best Boy","Focus Puller","Boom Operator","Sound Engineer",
            "Music Producer","Record Label Executive","A&R Representative","Tour Manager",
            "Road Manager","Concert Promoter","Talent Agent","Casting Director","Talent Scout"
            ,
            // Additional jobs
            "Surgeon","Anesthesiologist","Radiologist","Cardiologist","Neurologist",
            "Oncologist","Pediatrician","Dermatologist","Ophthalmologist","Orthopedist",
            "Psychiatrist","Psychologist","Therapist","Counselor","Social Worker",
            "Paramedic","EMT","Veterinarian","Vet Technician","Zoo Keeper",
            "Wildlife Biologist","Marine Biologist","Ecologist","Botanist","Zoologist",
            "Geologist","Meteorologist","Oceanographer","Astronomer","Astrophysicist",
            "Chemist","Biochemist","Microbiologist","Geneticist","Neuroscientist",
            "Physicist","Mathematician","Statistician","Economist","Sociologist",
            "Anthropologist","Archaeologist","Historian","Political Scientist","Philosopher",
            "Judge","Prosecutor","Defense Attorney","Paralegal","Court Reporter",
            "Patent Attorney","Immigration Lawyer","Tax Attorney","Notary Public",
            "Real Estate Agent","Property Manager","Land Surveyor","Urban Planner",
            "Civil Engineer","Structural Engineer","Mechanical Engineer","Electrical Engineer",
            "Chemical Engineer","Aerospace Engineer","Nuclear Engineer","Biomedical Engineer",
            "Robotics Engineer","Software Engineer","Network Engineer","Data Scientist",
            "Machine Learning Engineer","AI Researcher","Business Analyst","Financial Analyst",
            "Investment Banker","Portfolio Manager","Stockbroker","Financial Advisor",
            "Actuary","Auditor","Accountant","Bookkeeper","Supply Chain Manager",
            "Logistics Manager","Operations Manager","Project Manager","Product Manager",
            "Marketing Manager","Brand Manager","Content Writer","Technical Writer",
            "Copywriter","Editor","Proofreader","Translator","Interpreter","Librarian",
            "Archivist","Curator","Art Director","Graphic Designer","Illustrator",
            "Animator","Motion Designer","3D Artist","VFX Artist","Game Designer",
            "UX Designer","UI Designer","Interior Designer","Fashion Designer",
            "Makeup Artist","Hair Stylist","Personal Trainer","Yoga Instructor",
            "Swimming Coach","Tennis Coach","Golf Instructor","Music Teacher",
            "Driving Instructor","Flight Instructor","Sous Chef","Pastry Chef",
            "Barista","Sommelier","Mixologist","Event Planner","Wedding Planner",
            "DJ","Comedian","Magician","Stuntman","Voice Actor","Radio Host",
            "News Anchor","Photojournalist","Videographer","Cinematographer",
            "Sound Engineer","Music Producer","Talent Agent","Casting Director"
    };

    // ── SPORTS & GAMES (500+) ─────────────────────────────────────────────────
    private static final String[] SPORTS = {
            "Football","Basketball","Tennis","Volleyball","Swimming","Boxing","Karate",
            "Running","Cycling","Surfing","Gymnastics","Goal","Penalty","World Cup",
            "Olympics","Skateboard","Roller Skates","Dumbbell","Treadmill","Soccer",
            "Baseball","Softball","Cricket","Rugby","American Football","Canadian Football",
            "Australian Rules Football","Gaelic Football","Hurling","Camogie","Handball",
            "Field Hockey","Ice Hockey","Roller Hockey","Bandy","Floorball","Lacrosse",
            "Water Polo","Polo","Canoe Polo","Disc Golf","Ultimate Frisbee","Dodgeball",
            "Kickball","Tetherball","Four Square","Hopscotch","Tag","Hide and Seek",
            "Capture the Flag","Red Light Green Light","Simon Says","Musical Chairs",
            "Duck Duck Goose","Freeze Tag","British Bulldog","Bullrush","Tug of War",
            "Sack Race","Egg and Spoon Race","Three Legged Race","Wheelbarrow Race",
            "Relay Race","Hurdles","High Jump","Long Jump","Triple Jump","Pole Vault",
            "Shot Put","Discus","Hammer Throw","Javelin","Decathlon","Heptathlon",
            "Pentathlon","Modern Pentathlon","Triathlon","Duathlon","Aquathlon",
            "Ironman","Sprint Triathlon","Olympic Triathlon","Half Ironman",
            "Marathon","Half Marathon","10K","5K","Fun Run","Obstacle Course Race",
            "Mud Run","Spartan Race","Tough Mudder","Color Run","Glow Run","Night Run",
            "Trail Running","Ultra Marathon","Ultrarunning","Fell Running","Hash Running",
            "Race Walking","Nordic Walking","Hiking","Backpacking","Mountaineering",
            "Rock Climbing","Free Solo","Bouldering","Top Rope","Lead Climbing","Speed Climbing",
            "Rappelling","Abseiling","Via Ferrata","Canyoneering","Caving","Spelunking",
            "White Water Rafting","Kayaking","Canoeing","Stand Up Paddleboarding",
            "Windsurfing","Kitesurfing","Paragliding","Hang Gliding","Skydiving",
            "Base Jumping","Wing Suit Flying","Bungee Jumping","Cliff Diving","Waterfall Rappelling",
            "Scuba Diving","Freediving","Snorkeling","Spearfishing","Underwater Hockey",
            "Synchronized Swimming","Artistic Swimming","Diving","Platform Diving",
            "Springboard Diving","High Diving","Night Snorkeling","Cave Diving",
            "Surfing","Bodyboarding","Skimboarding","Boogie Boarding","Wake Surfing",
            "Wakeboarding","Waterskiing","Barefoot Waterskiing","Cable Wakeboarding",
            "Rowing","Dragon Boat Racing","Outrigger Canoe Racing","Sailing","Racing",
            "Regatta","Yacht Racing","Dinghy Sailing","Windsurfing Race","Kite Racing",
            "Motorboat Racing","Jet Ski Racing","Hydroplane Racing","Offshore Powerboat",
            "Chess","Checkers","Draughts","Go","Shogi","Xiangqi","Mancala","Backgammon",
            "Mahjong","Dominoes","Cards","Poker","Bridge","Rummy","Gin Rummy","Canasta",
            "Cribbage","Blackjack","Baccarat","Solitaire","Snap","War","Old Maid","Crazy Eights",
            "Uno","Skip-Bo","Phase 10","Sequence","Scrabble","Boggle","Word Search",
            "Crossword","Sudoku","Kakuro","Picross","Nonogram","Logic Puzzle","Riddle",
            "Jigsaw Puzzle","3D Puzzle","Rubik's Cube","Tangram","Peg Solitaire",
            "Tower of Hanoi","Sliding Puzzle","Maze","Labyrinth","Escape Room",
            "Dungeons and Dragons","Pathfinder","Warhammer","Magic the Gathering",
            "Pokémon TCG","Yu-Gi-Oh","Hearthstone","Legends of Runeterra","Gwent",
            "Ticket to Ride","Catan","Carcassonne","Pandemic","Codenames","Dixit",
            "Splendor","Wingspan","Terraforming Mars","Gloomhaven","Arkham Horror",
            "Exploding Kittens","Cards Against Humanity","Taboo","Pictionary","Charades",
            "Trivial Pursuit","Jeopardy","Who Wants to be a Millionaire","Wheel of Fortune",
            "Deal or No Deal","The Price is Right","Family Feud","Name That Tune",
            "20 Questions","Two Truths and a Lie","Never Have I Ever","Truth or Dare",
            "Spin the Bottle","Beer Pong","Flip Cup","Quarters","Jenga","Croquet",
            "Bocce","Pétanque","Horseshoes","Cornhole","Ladder Toss","Kan Jam",
            "Spikeball","Pickleball","Padel","Squash","Racquetball","Badminton",
            "Table Tennis","Foosball","Air Hockey","Shuffleboard","Billiards","Pool",
            "Snooker","Darts","Archery","Rifle Shooting","Pistol Shooting","Skeet Shooting",
            "Trap Shooting","Biathlon","Shooting Sport","Fencing","Sabre","Epee","Foil",
            "Judo","Jiu-Jitsu","Brazilian Jiu-Jitsu","Wrestling","Greco-Roman Wrestling",
            "Freestyle Wrestling","Sumo","Muay Thai","Kickboxing","Savate","Capoeira",
            "Taekwondo","Tang Soo Do","Hapkido","Kendo","Iaido","Ninjutsu","Aikido",
            "Kung Fu","Wing Chun","Tai Chi","Wushu","Sambo","Krav Maga","Systema",
            "Jeet Kune Do","Silat","Eskrima","Arnis","Kali","Gatka","Kushti","Lethwei",
            "CrossFit","HIIT","Tabata","Plyometrics","Calisthenics","Powerlifting",
            "Olympic Weightlifting","Strongman","Arm Wrestling","Grip Sport","Pull-ups",
            "Dips","Push-ups","Burpees","Jumping Jacks","Mountain Climbers","Plank",
            "Yoga","Hatha Yoga","Vinyasa Yoga","Ashtanga Yoga","Kundalini Yoga",
            "Yin Yoga","Restorative Yoga","Hot Yoga","Bikram Yoga","Power Yoga",
            "Ballet","Contemporary Dance","Jazz Dance","Tap Dance","Hip Hop Dance",
            "Breakdancing","Ballroom Dance","Latin Dance","Salsa","Bachata","Merengue",
            "Cumbia","Tango","Waltz","Foxtrot","Quickstep","Viennese Waltz","Paso Doble",
            "Samba","Cha Cha","Jive","Flamenco","Bollywood Dance","K-pop Dance",
            "Ice Skating","Figure Skating","Ice Dancing","Speed Skating","Short Track",
            "Curling","Ice Hockey","Broomball","Ringette","Bandy","Bobsled","Luge","Skeleton",
            "Ski Jumping","Nordic Combined","Cross-Country Skiing","Biathlon Skiing",
            "Alpine Skiing","Downhill Skiing","Slalom","Giant Slalom","Super-G",
            "Freestyle Skiing","Moguls","Aerials","Halfpipe Skiing","Slopestyle Skiing",
            "Snowboarding","Halfpipe Snowboarding","Slopestyle Snowboarding","Big Air",
            "Snowshoeing","Dog Sledding","Skijoring","Snowkiting","Telemark Skiing",
            "Esports","Counter-Strike","Valorant","League of Legends","Dota 2",
            "Overwatch","Fortnite","PUBG","Apex Legends","Call of Duty","Halo",
            "StarCraft","Warcraft","Hearthstone","Rocket League","FIFA","PES",
            "NBA 2K","Madden","Tekken","Street Fighter","Mortal Kombat","Super Smash Bros"
            ,
            // Additional sports
            "Archery","Rifle Shooting","Pistol Shooting","Fencing","Sabre","Epee","Foil",
            "Judo","Jiu-Jitsu","Brazilian Jiu-Jitsu","Wrestling","Sumo","Muay Thai",
            "Kickboxing","Capoeira","Taekwondo","Krav Maga","CrossFit","HIIT","Pilates",
            "Powerlifting","Olympic Weightlifting","Strongman","Arm Wrestling","Calisthenics",
            "Rock Climbing","Free Solo","Bouldering","Rappelling","Canyoneering",
            "White Water Rafting","Kayaking","Canoeing","Stand Up Paddleboarding",
            "Windsurfing","Kitesurfing","Paragliding","Hang Gliding","Skydiving","Base Jumping",
            "Scuba Diving","Freediving","Snorkeling","Synchronized Swimming","Rowing",
            "Dragon Boat Racing","Sailing","Motorboat Racing","Jet Ski Racing",
            "Chess","Checkers","Go","Backgammon","Mahjong","Poker","Bridge","Scrabble",
            "Boggle","Crossword","Sudoku","Rubik's Cube","Jigsaw Puzzle","Escape Room",
            "Catan","Pandemic","Codenames","Ticket to Ride","Trivial Pursuit",
            "Cornhole","Bocce","Pétanque","Horseshoes","Ladder Toss","Spikeball",
            "Pickleball","Padel","Squash","Racquetball","Table Tennis","Foosball",
            "Air Hockey","Shuffleboard","Billiards","Pool","Snooker","Darts",
            "Ice Skating","Figure Skating","Speed Skating","Curling","Bobsled","Luge",
            "Ski Jumping","Cross-Country Skiing","Alpine Skiing","Freestyle Skiing",
            "Snowboarding","Dog Sledding","Esports","Rocket League","FIFA","Tekken"
    };

    // ── SCHOOL & STUDY (500+) ─────────────────────────────────────────────────
    private static final String[] SCHOOL = {
            "Exam","Homework","Teacher","Classroom","Project","Presentation","Grade",
            "Diploma","University","Library","Scholarship","Calculator","History","Math",
            "Physics","Chemistry","Biology","English","Arabic","French","Geography",
            "Whiteboard","Blackboard","Desk","Student","Principal","Notebook Paper",
            "Highlighter","Quiz","Lecture","Campus","Laboratory","Thesis","Internship",
            "Algebra","Geometry","Trigonometry","Calculus","Statistics","Probability",
            "Number Theory","Linear Algebra","Differential Equations","Topology",
            "Analysis","Abstract Algebra","Set Theory","Logic","Proof","Theorem",
            "Axiom","Lemma","Corollary","Conjecture","Hypothesis","Experiment",
            "Observation","Conclusion","Data Collection","Sample","Population","Variable",
            "Control Group","Test Group","Placebo","Peer Review","Citation","Reference",
            "Bibliography","Footnote","Abstract","Introduction","Literature Review",
            "Methodology","Results","Discussion","Conclusion","Appendix","Index",
            "Table of Contents","Glossary","Preface","Foreword","Acknowledgments",
            "Dedication","Epigraph","Cover Page","Title Page","Header","Footer",
            "Page Number","Margin","Indent","Paragraph","Topic Sentence","Thesis Statement",
            "Supporting Evidence","Counterargument","Rebuttal","Transition","Conclusion Sentence",
            "Essay","Argumentative Essay","Persuasive Essay","Narrative Essay","Descriptive Essay",
            "Expository Essay","Analytical Essay","Compare and Contrast","Cause and Effect",
            "Problem Solution","Definition Essay","Process Essay","Reflective Essay",
            "Research Paper","Term Paper","Lab Report","Case Study","Book Report",
            "Book Review","Literary Analysis","Poetry Analysis","Film Analysis",
            "Poem","Haiku","Sonnet","Free Verse","Ballad","Ode","Elegy","Epic",
            "Short Story","Novel","Novella","Graphic Novel","Play","Script","Screenplay",
            "Memoir","Autobiography","Biography","Travelogue","Blog Post","Article",
            "Opinion Piece","Editorial","Feature Story","News Story","Interview",
            "Press Release","White Paper","Technical Report","Grant Proposal","Business Plan",
            "Academic","Scientific Paper","Monograph","Textbook","Workbook","Study Guide",
            "Flashcard","Mind Map","Outline","Summary","Note-taking","Annotation",
            "Highlighter","Sticky Note","Color Coding","Cornell Notes","Mind Mapping",
            "Concept Map","Venn Diagram","Flow Chart","Timeline","Graphic Organizer",
            "KWL Chart","T-chart","Pros and Cons","Brainstorming","Clustering",
            "Freewriting","Journaling","Reflective Writing","Critical Thinking",
            "Problem Solving","Creative Thinking","Analytical Thinking","Systems Thinking",
            "Design Thinking","Computational Thinking","Metacognition","Growth Mindset",
            "Fixed Mindset","Learning Style","Visual Learner","Auditory Learner",
            "Kinesthetic Learner","Reading Writing Learner","Multiple Intelligences",
            "Memory Technique","Mnemonic","Spaced Repetition","Active Recall","Interleaving",
            "Elaborative Interrogation","Concrete Examples","Dual Coding","Retrieval Practice",
            "Pomodoro Technique","Time Blocking","Eisenhower Matrix","Getting Things Done",
            "Kanban Board","Habit Tracker","Goal Setting","SMART Goals","OKRs","KPIs",
            "Attendance","Tardy","Absence","Excuse Note","Permission Slip","Field Trip",
            "Substitute Teacher","Supply Teacher","Teaching Assistant","Classroom Aide",
            "Special Needs","IEP","504 Plan","Gifted Program","Remedial Class",
            "Detention","Suspension","Expulsion","Honor Roll","Dean's List","Valedictorian",
            "Salutatorian","Class Rank","GPA","Weighted GPA","Unweighted GPA",
            "SAT","ACT","PSAT","GRE","GMAT","LSAT","MCAT","TOEFL","IELTS","Cambridge",
            "AP Exam","IB Exam","A-Level","O-Level","GCSE","Baccalaureate","Abitur",
            "Matura","Gaokao","University Entrance Exam","Placement Test","Aptitude Test",
            "IQ Test","Personality Test","Interest Inventory","Career Assessment",
            "College Application","Personal Statement","Letter of Recommendation",
            "Application Essay","Common App","Coalition App","Early Decision","Early Action",
            "Regular Decision","Rolling Admission","Wait List","Acceptance Letter",
            "Rejection Letter","Financial Aid","FAFSA","Scholarship Application","Grant",
            "Work-Study","Student Loan","Tuition","Room and Board","Meal Plan","Stipend",
            "Teaching Fellowship","Research Assistantship","Graduate Assistantship",
            "Postdoctoral Fellowship","Sabbatical","Tenure","Tenure Track","Adjunct",
            "Visiting Professor","Guest Lecturer","Professor Emeritus","Academic Chair",
            "Department Head","Dean","Provost","Chancellor","President","Board of Trustees",
            "Student Government","Student Union","Club","Society","Honor Society",
            "Greek Life","Fraternity","Sorority","Dormitory","Residence Hall","Suite",
            "Single Room","Double Room","Triple Room","Quad","Community Bathroom",
            "Communal Kitchen","Study Room","Common Room","Laundry Room","Mail Room",
            "Dining Hall","Cafeteria","Meal Swipe","Dining Dollars","Flex Points",
            "Recreation Center","Fitness Center","Student Health Center","Counseling Center",
            "Writing Center","Math Lab","Science Lab","Computer Lab","Language Lab",
            "Art Studio","Music Practice Room","Theater","Auditorium","Chapel",
            "Bookstore","Convenience Store","ATM","Copy Center","Post Office Box",
            "Parking Lot","Shuttle Bus","Campus Map","Campus Tour","Orientation",
            "Welcome Week","Commencement","Graduation Ceremony","Diploma","Transcript"
            ,
            // Additional school
            "Algebra","Geometry","Trigonometry","Calculus","Statistics","Probability",
            "Number Theory","Linear Algebra","Differential Equations","Hypothesis",
            "Experiment","Observation","Data Collection","Peer Review","Citation",
            "Bibliography","Abstract","Introduction","Literature Review","Methodology",
            "Results","Discussion","Appendix","Glossary","Table of Contents",
            "Essay","Argumentative Essay","Persuasive Essay","Narrative Essay","Research Paper",
            "Lab Report","Case Study","Book Report","Book Review","Literary Analysis",
            "Poem","Sonnet","Free Verse","Haiku","Short Story","Novel","Play","Script",
            "Memoir","Autobiography","Biography","Blog Post","Article","Editorial",
            "Flashcard","Mind Map","Outline","Summary","Note-taking","Annotation",
            "Venn Diagram","Flow Chart","Timeline","Graphic Organizer","Brainstorming",
            "Critical Thinking","Problem Solving","Creative Thinking","Growth Mindset",
            "Spaced Repetition","Active Recall","Pomodoro Technique","Time Blocking",
            "Attendance","Field Trip","Substitute Teacher","Teaching Assistant","IEP",
            "Honor Roll","Valedictorian","Salutatorian","GPA","SAT","ACT","GRE","GMAT",
            "TOEFL","IELTS","AP Exam","IB Exam","College Application","Personal Statement",
            "Letter of Recommendation","Financial Aid","Scholarship Application","Student Loan",
            "Tuition","Dormitory","Residence Hall","Dining Hall","Study Room","Common Room",
            "Student Government","Club","Honor Society","Fraternity","Sorority",
            "Commencement","Graduation Ceremony","Transcript","Degree","Certificate",
            "Associate Degree","Bachelor's Degree","Master's Degree","Doctorate","PhD",
            "Postdoctoral","Tenure","Sabbatical","Professor Emeritus","Department Head",
            "Dean","Chancellor","Board of Trustees","Office Hours","Syllabus","Rubric",
            "Grading Scale","Pass or Fail","Credit Hours","Elective","Required Course",
            "Major","Minor","Double Major","Pre-Med","Pre-Law","Undeclared","Transfer",
            "Exchange Student","Study Abroad","Gap Year","Dual Enrollment","Online Class",
            "Distance Learning","Hybrid Course","Asynchronous","Synchronous","Webinar",
            "Virtual Classroom","Learning Management System","Plagiarism","Academic Integrity",
            "Honor Code","Citation Style","APA","MLA","Chicago","Turnitin","Peer Tutoring"
    };

    // ── RANDOM & FUN (500+) ───────────────────────────────────────────────────
    private static final String[] FUN = {
            "Secret","Shadow","Fire","Ice","Storm","Wind","Sun","Moon","Star","Cloud",
            "Rain","Thunder","Dream","Money","Power","Luck","Freedom","Challenge",
            "Winner","Hero","Villain","Trap","Ghost","Zombie","Alien","Treasure",
            "Island","Prison","Explosion","Magic","Virus","King","Queen","Crown",
            "Sword","Shield","Dragon","Monster","Treasure Chest","Labyrinth",
            "Time Machine","Portal","Spaceship","Galaxy","Planet","Meteor","Comet",
            "Superhero","Detective","Adventure","Battle","Camping","Carnival",
            "Champion","Clown","Concert","Dance","Festival","Fireworks","Friendship",
            "Game Night","Graduation","Holiday","Journey","Legend","Marathon",
            "Memory","Mission","Mystery","Party","Road Trip","Rocket","Safari",
            "Sleepover","Snow","Summer","Sunset","Surprise","Talent Show","Teamwork",
            "Tournament","Vacation","Victory","Village","Waterpark","Wedding","Weekend",
            "Workshop","Adrenaline","Ambush","Amnesia","Ancient","Apocalypse","Artifact",
            "Assassin","Astral","Asylum","Auction","Avalanche","Bandit","Betrayal",
            "Black Hole","Blackout","Blizzard","Blueprint","Bounty","Bravery","Breakthrough",
            "Brotherhood","Bunker","Chaos","Cipher","Clue","Code Red","Conspiracy",
            "Countdown","Covert","Crisis","Crossroads","Cryptic","Cursed","Darkness",
            "Dawn","Daybreak","Deadline","Deception","Destiny","Dimension","Disguise",
            "Doomsday","Doppelganger","Eclipse","Escape","Exile","Explosion","Exposed",
            "Fable","Fate","Fear","Feud","Flashback","Forbidden","Force Field",
            "Fortress","Fugitive","Galaxy Quest","Game Over","Gamemaster","Gladiator",
            "Glitch","Goblin","Golden Ticket","Grail","Greed","Grudge","Guardian",
            "Guillotine","Gunpowder","Haunted","Heist","Hollow","Horizon","Hostage",
            "Hourglass","Hydra","Illusion","Immortal","Impostor","Infiltrate","Infinity",
            "Jungle Hunt","Last Stand","Lava","Lightning","Lost World","Maelstrom",
            "Maze Runner","Mercenary","Mirage","Mischief","Moonlight","Mutant","Nebula",
            "Nemesis","Ninja","Nuclear","Oath","Obsession","Oracle","Outbreak","Outlaw",
            "Paradox","Phantom","Phoenix","Plague","Poison","Power Plant","Prophecy",
            "Prototype","Pursuit","Puzzle","Quicksand","Quicksilver","Radar","Rampage",
            "Rebellion","Redemption","Revelation","Revenge","Revolution","Riddle","Rogue",
            "Ruin","Sacrifice","Samurai","Sanctuary","Scorpion","Secret Society",
            "Serum","Shapeshifter","Siege","Signal","Simulation","Skeleton","Skull",
            "Sky Fortress","Sleeper Agent","Smoke Screen","Sniper","Sorcerer","Soul",
            "Specter","Spy Network","Stargate","Stealth","Stolen Identity","Stormtrooper",
            "Sting Operation","Subterranean","Sunken City","Supernova","Suspense",
            "Syndicate","Teleport","Tempest","Thunderstrike","Time Loop","Time Warp",
            "Titan","Tornado","Traitor","Trigger","Trojan Horse","Tsunami","Twilight",
            "Undercover","Underground","Undying","Unmasked","Uprising","Venom","Verdict",
            "Vigilante","Vortex","War Room","Warlord","Wasteland","Whirlpool","Wildfire",
            "Witch","Wormhole","Wrath","Zero Hour","Zombie Horde","Abandoned","Abyss",
            "Ace","Age of Chaos","Agent Zero","Almanac","Ambiguity","Ancient Curse",
            "Ancient Ruins","Angel","Anomaly","Antagonist","Antidote","Anvil","Arcane",
            "Archeology","Arctic Base","Arena","Armory","Arrest","Arsenal","Astral Plane",
            "Atomic","Aurora","Avalanche Zone","Awakening","Axis","Backstab","Backtrack",
            "Badge","Bait","Battleground","Beacon","Beast Mode","Belonging","Betrayed",
            "Biohazard","Black Market","Black Ops","Blackmail","Blazing","Blind Spot",
            "Blood Moon","Bloodline","Blowout","Blue Flame","Body Double","Bomb Squad",
            "Bouncer","Breakout","Breeder","Bridge Collapse","Broken Alliance",
            "Brotherhood of Shadows","Bug Out","Bullet Proof","Buried Alive","Burning Bridge",
            "Burning City","Bushcraft","Bypass","Cage Fight","Calling Card","Camouflage",
            "Canopy","Cardinal Rule","Carrier","Cat and Mouse","Catalyst","Cave System",
            "Celebrity","Cell","Century","Chaos Theory","Chemical Weapon","Chosen One",
            "Chrome","Classified","Clean Slate","Cliffhanger","Clone","Close Call",
            "Cold War","Collapse","Collision","Combat Zone","Command Center","Communion",
            "Conflict","Conquer","Containment","Contract Killer","Controlled Burn",
            "Corruption","Counterintelligence","Coup","Cover Story","Coward","Crash Landing",
            "Criminal Mastermind","Critical Mass","Crowd Control","Crusade","Crypt",
            "Crystal Ball","Cult","Cutthroat","Cyber Attack","Dark Matter","Dark Side",
            "Data Breach","Dead Drop","Dead End","Deadly Sin","Deathrow","Debris Field",
            "Decoy","Defector","Demolition","Desolation","Devastation","Diversion",
            "Divided Loyalty","DNA Test","Dogfight","Domination","Double Agent","Double Cross",
            "Double Jeopardy","Downfall","Dragon's Lair","Dread","Drone Strike",
            "Duel","Dust Storm","Dynamic Entry","Dystopia","Eagle Eye","Earthquake",
            "Echoes","Edge of Darkness","Electromagnetic Pulse","Emergency Protocol",
            "Empire","Encrypted Message","Endgame","Endless Loop","Enemy Territory",
            "Enigma","Entity","Eruption","Espionage","Eternal","Evidence","Exile",
            "Extinction","Eye of the Storm","False Flag","False Identity","Fallout",
            "Familiar","Fearless","Field Agent","Final Boss","First Strike","Flash Point",
            "Flashbang","Flaw","Forbidden Zone","Force Multiplier","Foreign Agent"
            ,
            // Additional fun
            "Paradox","Phantom","Phoenix","Plague","Prophecy","Pursuit","Rebellion",
            "Redemption","Revelation","Revenge","Revolution","Rogue","Sacrifice",
            "Samurai","Sanctuary","Siege","Simulation","Skeleton","Skull","Sniper",
            "Sorcerer","Soul","Specter","Spy Network","Stealth","Tempest","Titan",
            "Tornado","Traitor","Trojan Horse","Tsunami","Twilight","Undercover",
            "Underground","Uprising","Venom","Verdict","Vigilante","Vortex",
            "Warlord","Wasteland","Wildfire","Witch","Wormhole","Zero Hour",
            "Abandoned","Abyss","Ancient Curse","Ancient Ruins","Anomaly","Antidote",
            "Arcane","Awakening","Betrayal","Black Market","Blackmail","Blood Moon",
            "Bounty","Bunker","Chaos","Cipher","Conspiracy","Countdown","Covert",
            "Cursed","Darkness","Deception","Destiny","Dimension","Disguise","Doomsday",
            "Eclipse","Exile","Fable","Fate","Forbidden","Fortress","Fugitive",
            "Gladiator","Glitch","Goblin","Haunted","Heist","Hostage","Illusion",
            "Immortal","Infiltrate","Last Stand","Lava","Maelstrom","Mercenary",
            "Mutant","Nemesis","Ninja","Outbreak","Outlaw","Power Plant","Prototype"
    };

    private static final java.util.Map<Theme, String[]> MAP = new java.util.EnumMap<>(Theme.class);
    static {
        MAP.put(Theme.OBJECTS, OBJECTS);
        MAP.put(Theme.PLACES,  PLACES);
        MAP.put(Theme.FOOD,    FOOD);
        MAP.put(Theme.TECH,    TECH);
        MAP.put(Theme.ANIMALS, ANIMALS);
        MAP.put(Theme.JOBS,    JOBS);
        MAP.put(Theme.SPORTS,  SPORTS);
        MAP.put(Theme.SCHOOL,  SCHOOL);
        MAP.put(Theme.FUN,     FUN);
    }

    private static final Random RANDOM = new Random();

    public static String getRandom(List<Theme> selectedThemes) {
        List<String> pool = new ArrayList<>();
        List<Theme> themes = (selectedThemes == null || selectedThemes.isEmpty())
                ? java.util.Arrays.asList(Theme.values()) : selectedThemes;
        for (Theme t : themes) {
            String[] words = MAP.get(t);
            if (words != null) for (String w : words) pool.add(w);
        }
        if (pool.isEmpty()) return "Mystery";
        return pool.get(RANDOM.nextInt(pool.size()));
    }

    public static String getRandom() {
        return getRandom(null);
    }

    public static String[] getWordsForTheme(Theme t) {
        return MAP.getOrDefault(t, new String[0]);
    }

    public static int totalWords() {
        int count = 0;
        for (String[] arr : MAP.values()) count += arr.length;
        return count;
    }
}